### ISSUE TITLE
Support for NEON

### ISSUE THREAD

**Issue by oskargargas** [pokkinandpup/TesseractBuild#1]
Hi,

does this compile script support NEON vector optimizations? I'll briefly looked how it works and get lost with patching configure scripts.

**Comment by hexdreamer** [comment]
According to this, NEON is automatically detected and used: 

https://github.com/tesseract-ocr/tesseract/issues/519

**Comment by oskargargas** [comment]
Ok, I partially agree. There is one thing that makes me unsure. 

In original Tesseract configure script there is a check for presence of Accelerate framework:
https://github.com/tesseract-ocr/tesseract/blob/main/configure.ac#L313

which leads to log:
`checking if -framework Accelerate works... yes`

and setting preprocessor var `HAVE_FRAMEWORK_ACCELERATE`
which is later used to enable SIMD/NEON code paths:
https://github.com/tesseract-ocr/tesseract/blob/60fd2b4abaa9c5c5c42d32db57576bc95d28a78a/src/arch/simddetect.cpp#L34

That's what I understand as automatic detection mentioned by @stweil. In this build script it looks like check for Accelerate is being rid off and for sure it doesn't show in logs. Am I missing something?

**Comment by stweil** [comment]
The Accelerate framework for Apple is never used by default and unrelated to the support for NEON.

**Comment by oskargargas** [comment]
I understand, maybe I get lost because of where it is used. May I asked what is it used for? Should I pursue a build using Accelerate or one without it is good enough (in performance terms)?

**Comment by stweil** [comment]
I added the Accelerate framework support to check how it performs on new platforms like Apple's M1. The performance on Intel and M1 MacBooks was nearly as good as Tesseract's own implementation for AVX2 (Intel) or NEON (M1). So there is currently no reason to use the framework. That might change with future Apple hardware or new versions of the framework.

**Comment by oskargargas** [comment]
Thank you for the explanation. Everything is clear now! I'm closing the issue
